[package]
name = "ToyP_CryptoCurrency"
version = "0.1.0"
edition = "2018"
authors = ["YoungKim <kimyk0120@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"